gems:
  - jemoji
  - jekyll-paginate

title: "Dev Blog"
description: >
   Trying to make this world a safer space.

email: control-owl[at]r-o0-t[dot]wtf
logo: "/assets/images/logo.jpg"
float_logo: true

cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Control Owl'
author: 'Control Owl'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/control-owl/qr2m
    desc:	QR2M
    share_url:
    share_title:
    share_link:

  # - icon:	twitter
  #   url:	https://twitter.com/
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="