gems:
  - jemoji
  - jekyll-paginate

title: "Control Owl"
description: >
   Trying to make this world a safer place

email: control-owl[at]r-o0-t[dot]wtf
cover: "/assets/images/header.jpg"

logo: "/assets/images/logo.jpg"
float_logo: true

cover: "/assets/images/header.jpg"

name: 'Control Owl'
author: 'Control Owl'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://https://control-owl.github.io"
baseurl: ""

# twitter_handle: '@'
disqus: controlowl
#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/control-owl/qr2m
    desc:	QR2M
    share_url:
    share_title:
    share_link:

# twitter_handle: '@'
# google_analytics: UA-XXXXX-X

# social icons and sharing options
  # - icon:	twitter
  #   url:	https://twitter.com/
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="