gems:
  - jemoji
  - jekyll-paginate
  - bourbon

title: "Control Owl"
description: >
   Trying to make this world a safer place

email: control-owl[at]r-o0-t[dot]wtf
cover: "/assets/images/header.jpg"

logo: "/assets/images/logo.jpg"
float_logo: true

cover: "/assets/images/header.jpg"

name: 'Control Owl'
author: 'Control Owl'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "https://control-owl.github.io"
baseurl: ""

disqus: control-owl

social:
  - icon:	github
    url:	https://github.com/control-owl
    desc:	GitHub
    share_url:
    share_title:
    share_link: